spring:
  application:
    name: eureka-service
server:
  port: 8767
  
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8767/eureka/
    fetch-registry: false
    register-with-eureka: false
     